Added two components for Data Presentation; InsightDisplay and StatDisplay
cs3203-team1/goodmeh-frontend pull request #19
Opened 2024-09-12 15:36 UTC by SethCKL

Created two components with MantineUI to assist in our Data Presentation component.

Currently prototype version, to be expanded and tweaked when connected with real back end data|

2024-09-13 08:38 UTC, zhekaiii requested changes
Thanks for the hard work, here are some early comments from me

2024-09-13 08:38 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.module.css
> +}
Btw bold is the same as font-weight: 700 so you can use whichever you prefer

2024-09-13 08:38 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.module.css
> +.stat {
Also this is another by (my) convention thing, but I forgot to mention that for class names I am adapting this naming convention https://getbem.com/naming/.

In short, BEM stands for Block__Element--modifier and that is exactly what the convention I follow looks like. So for the "Block" part I would name it the same as the component name, in this case `InsightDisplay`, and then the "Element" part would be like a 1-2 word thing to describe what it applies to, in this case `Stat` would be fine I guess. In this case no modifier but an example would be like `selected`. So in full it would be `InsightDisplay__Stat` and likewise need to update in the .tsx file to do `classes.InsightDisplay__Stat`.

2024-09-13 08:38 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.module.css
> +.stat {
And if you use scss you can actually do nesting like this!

```scss
// This used to be .root
.InsightDisplay {
  display: flex;
  background-image: linear-gradient(
    -60deg,
    var(--mantine-color-blue-4) 0%,
    var(--mantine-color-blue-7) 100%
  );
  padding: calc(var(--mantine-spacing-xl) * 1.5);
  border-radius: var(--mantine-radius-md);

  // This means .InsightDisplay__Stat
  &__Stat {
    flex: 1;

    & + & {
      padding-left: var(--mantine-spacing-xl);
      margin-left: var(--mantine-spacing-xl);
      border-left: rem(1px) solid var(--mantine-color-blue-3);
    }
  }

  @media (max-width: $mantine-breakpoint-sm) {
    flex-direction: column;

    &__Stat {
      & + & {
        padding-left: 0;
        margin-left: 0;
        border-left: 0;
        padding-top: var(--mantine-spacing-xl);
        margin-top: var(--mantine-spacing-xl);
        border-top: rem(1px) solid var(--mantine-color-blue-3);
      }
    }
  }
}
```

2024-09-13 08:38 UTC, zhekaiii commented on src/features/Consumer/components/StatDisplay.module.css
> +  .label {
`.label` might not be needed if you shift this to ff prop. Also can you configure your autoformatter and try enabling autoformat on save and save this file to verify that it works?

2024-09-13 08:38 UTC, zhekaiii commented on src/features/Consumer/components/StatDisplay.tsx
> +    </Container>
Seems a bit excessive to have 3 containers for the stats HAHAHA what are you trying to do here?

2024-09-13 17:27 UTC, SethCKL commented on src/features/Consumer/components/InsightDisplay.module.css
> +}
i see! so does this mean that we can get rid of CSS files, and we can just take care of styling using what Mantine supports?

2024-09-13 17:35 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.module.css
> +}
Not necessarily! Css can still be used if for example we do it on native elements like div and such, or if we need to do some special thing like the `& + &` that you did

2024-09-13 18:10 UTC, SethCKL commented on src/features/Consumer/components/InsightDisplay.module.css
gotcha :D

2024-09-14 05:27 UTC, SethCKL commented on src/features/Consumer/components/StatDisplay.tsx
> +    </Container>
agreed, artifact carried it over from an initial prototype

2024-09-14 07:40 UTC, SethCKL commented on src/features/Consumer/components/StatDisplay.module.css
> +  .label {
shifted and actually removed the file as it's not needed anymore

2024-09-14 08:43 UTC, zhekaiii requested changes
Almost there, just some nits

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.module.scss
> +.stat {
Rmb to follow the class name convention!
```suggestion
.InsightDisplay__Stat {
```

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/StatDisplay.tsx
> +            }}
The `c` prop corresponds to the `color` style property and because it's a mantine component you can just do teal.6 or red.6 also!
```suggestion
            c={stat.diff > 0 ? "teal.6" : "red.6"}
```

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/StatDisplay.tsx
> +        style={{ height: "100%" }}
You can do
```suggestion
        h="100%"
```
But i suspect this is redundant and you can completely remove it

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/StatDisplay.tsx
> +        <Group justify="apart" style={{ height: "100%" }}>
Actually if you see ah, you have Paper and then Group right, both are kinda like containers hor. You can actually ask Paper to use Group as the root component and then pass in whatever props you want to the Paper component and it's all type checked.

```tsx
      <Paper
        withBorder
        p="xl"
        radius="md"
        key={stat.title}
        component={Group}
        justify="space-between"
      >
```

Also again I think the height 100% is redundant and also i think apart doesn't exist for justify? I think what you're thinking of is space-between.

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.tsx
> +        className={classes.count}
This className no need already right? Same for the other classes below

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.tsx
> +        size="32px"
If i'm not wrong xl is 2rem which is 32px

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.tsx
> +        c="var(--mantine-color-blue-0)"
```suggestion
        c="blue.0"
```

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.tsx
> +        mt={5}
Can we use the sm md lg spacing for consistency? Unless there's a specific reason why you choose 5px

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.tsx
> +      className={classes.root}
This one can remove

2024-09-14 08:43 UTC, zhekaiii commented on src/features/Consumer/components/InsightDisplay.tsx
> +        backgroundImage:
Can just use `bg` prop for background. Unfortunately idk why mantine doesn't have a prop for borderRadius especially since they have sizes for that also, quite dumb.

2024-09-15 08:29 UTC, SethCKL commented on src/features/Consumer/components/InsightDisplay.tsx
> +        size="32px"
added more custom fontSizes in Theme.ts for this purpose, xl is actually 1.25 rem which isn't big enough for this element

2024-09-15 08:32 UTC, SethCKL commented on src/features/Consumer/components/InsightDisplay.tsx
> +        mt={5}
agreed

2024-09-15 08:36 UTC, SethCKL commented on src/features/Consumer/components/InsightDisplay.tsx
> +        className={classes.count}
good catch! did not notice

2024-09-15 10:05 UTC, zhekaiii approved these changes
LGTM, good first PR!

2024-09-15 10:07 UTC, merged